### ISSUE TITLE
DRAGEN v3.6.3

### ISSUE THREAD

**Issue by bollig** [aws-quickstart/quickstart-illumina-dragen#34]
Rebuild the quickstart with DRAGEN Complete Suite v3.6.3 (https://aws.amazon.com/marketplace/pp/B07CZ3F5HY)

**Comment by vsnyc** [comment]
Resolving this issue. We're updating it to the latest v3.7.5 in PR https://github.com/aws-quickstart/quickstart-illumina-dragen/pull/36
