### ISSUE TITLE
Add support of downloading pedigree table file from S3 when running Dragen in Pedigree Mode

### ISSUE THREAD

**Issue by ericpanyc** [aws-quickstart/quickstart-illumina-dragen#51]
Issue:
When running Dragen in pedigree mode, Dragen quickstart is not able to download the pedigree table from S3.
command submitted:
-f -r /ephemeral/Dragen_aws_test/dragen_ref/hs37d5/ --enable-joint-genotyping true --output-file-prefix M00022008-B-D_20220211-trio --output-directory /ephemeral/27545a9f-2acb-4d84-9a0f-00cd5d89ac7b --pedigree-file s3://bucket/M00022008-B-D_20220211/M00022008.ped --variant s3://bucket/M00022008-B-D_20220211.hard-filtered.gvcf.gz --variant s3://bucket/M00022006-B-D_20220211.hard-filtered.gvcf.gz --variant s3://bucket/M00022005-B-D_20220211.hard-filtered.gvcf.gz

Dragen log:
Assertion failed in ../src/host/dragen_api/file_io/pedigree.cpp line 24 -- false -- ERROR: Could not open pedigree file: s3://bucket/M00022008.ped

**Comment by vsnyc** [comment]
Addressed in #56
