### ISSUE TITLE
Update for stack (e.g template yaml file)

### ISSUE THREAD

**Issue by hmkim87** [aws-quickstart/quickstart-illumina-dragen#52]
Please update for ami id.

For example, 
ami-0a5a79a8ad1b66f36

**Comment by hmkim** [comment]
https://github.com/aws-quickstart/quickstart-illumina-dragen/pull/54

**Comment by hmkim87** [comment]
https://github.com/aws-quickstart/quickstart-illumina-dragen/pull/54/
